reddit = {
  "mu-lulli-choti" : "placeshitgoingon",
   "El__Sandwich" : "goINDIAgo", 
   "reasonable_yak5916" : "Accomplished420",
   "Big_chungus_slayer" : "your_mama_is_fat",
   "14dawrf3e3rfw" : "goINDIAgo",
   "void_will_loose" : "goINDIAgo",
   "mizkifsuckscock" : "goINDIAgo",
   "mizkifkmkb" : "goINDIAgo",
   "void_loser" : "goINDIAgo",
   "imsovamain69" : "imsovamain@69",
   "Cheap_Fly_7991" : "Accomplished420",
   "Tight_Map1719" : "Accomplished420",
   "No_List9598" : "Accomplished420",
   "Competitive-Cap5798" : "redditkapw",
   "DrDigBik69" : "unkimaakabsd",
   "DDrDreDaddyHell" : "Farquah57Joke",
   "FlimsyTurquoise" : "FlamesAre401",
   "Pure-Escape1749" : "12345678987654321",
   "Yoloyoloyolo35" : "dhuaghruehkalfi67",
   "curious_cupid" : "01257272",
   "INDIARPLACE" : "INDIARPLACE",
   "AnxietyPatient"  : "PillsForAnxiety",
   "IndiaFTWPLACE" : "indiaftw",
   "fuckyouswarm" : "goindiago2022",
   "Chbcdbhaxhb" : "duwu7^%4k",
   "Low-Scientist-2116" : "donkeyballs" ,
   "IndianPlaceBot" : "Indianplace1",
   "IndiaPlaceFTW" : "password123",
   "Indiantilesbot01" : "IndianTilesBot",  
   "Indiaplace1111" : "goINDIAgo",
   "Indiaplacewin111" : "goINDIAgo",
    "Peacockcreator" : "mudizifan",
   "F1Ace24": "TilesBest",
   "Feetysdeeltys" :  "thefeetushasbeendeleted",
    "Indiaforthewin01" : "password01",
    "I_N_D_I_A_O_P" : "password101"

}
